packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - esbuild
  - sharp

minimumReleaseAgeExclude:
  - turbo
  - '@turbo/darwin-64'
  - '@turbo/darwin-arm64'
  - '@turbo/linux-64'
  - '@turbo/linux-arm64'
  - '@turbo/windows-64'
  - '@turbo/windows-arm64'
