export const RESEARCH_JOB_TYPES = [
  'population.import.requested',
  'population.normalize.requested',
  'population.resolve.requested',
  'enrichment.bulk.requested',
  'enrichment.archive.requested',
  'research.priority.requested',
  'collection.run.requested',
  'collection.target.queued',
  'collection.page.retrieve',
  'collection.snapshot.persist',
  'collection.extraction.requested',
  'collection.coverage.recalculate',
  'intelligence.recalculation.requested',
  'research.run.execute',
  'research.run.pause',
] as const;

export type ResearchJobType = (typeof RESEARCH_JOB_TYPES)[number];

export const RESEARCH_EVENTS = [
  'population.source_registered',
  'population.import_created',
  'population.row_normalized',
  'population.organization_created',
  'population.organization_matched',
  'population.duplicate_flagged',
  'population.resolution_review_requested',
  'research.priority_calculated',
  'research.source_registered',
  'research.source_enabled',
  'research.source_suspended',
  'research.collection_run_created',
  'research.collection_run_started',
  'research.retrieval_completed',
  'research.retrieval_blocked',
  'research.retrieval_failed',
  'research.snapshot_created',
  'research.extraction_completed',
  'research.claim_proposed',
  'research.claim_accepted',
  'research.claim_corrected',
  'research.claim_rejected',
  'research.collection_run_completed',
  'research.collection_run_cancelled',
  'research.kill_switch_activated',
  'intelligence.recalculation_requested',
  'research_run.validating',
  'research_run.blocked',
  'research_run.queued',
  'research_run.started',
  'research_run.paused',
  'research_run.resumed',
  'research_run.cancelled',
  'research_run.completed',
  'research_run.kill_switch',
  'research_run.target_failed',
  'research_run.budget_exhausted',
] as const;

export type ResearchEventType = (typeof RESEARCH_EVENTS)[number];
